### ISSUE TITLE
[BUG] 2.7.0 - Please set the DNSPLUGIN variable to one of the following, works reverting to 2.6.0

### ISSUE THREAD

**Issue by cohenchris** [linuxserver/docker-swag#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the most recent update, my reverse proxy does not work with porkbun (at least). 

My docker container gives me an output listing the environment variables set, and then this message:

"Please set the DNSPLUGIN variable to one of the following:"

There is no further output. I have reverted to version 2.6.0 and everything works.

### Expected Behavior

Reverse proxy container starts and handles traffic.

### Steps To Reproduce

1. Update to the most recent version of swag, as of October 3, 2023
2. Run the docker-swag container
3. Observer the output listed above

### Environment

```markdown
- OS: Arch Linux
- How docker service was installed: distro's package manager
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up -d
```

### Container logs

```bash
"Please set the DNSPLUGIN variable to one of the following:"
```

**Comment by Roxedus** [comment]
Can replicate. looking into it.

**Comment by cohenchris** [comment]
> Can replicate. looking into it.

Thank you! Let me know if I can be of any help.

**Comment by CyberOxide** [comment]
I am having the same issue as cohenchris reported.  Only difference is I'm using 'cloudflare'.  Let me know if I can be of help.

**Comment by djcath** [comment]
confirmed using cloudflare plugin and issue presenting the same

**Comment by toddke** [comment]
having the same issue with DNSPLUGIN set to `google-domains`

**Comment by Roxedus** [comment]
Please test the `lspipepr/swag:2.7.0-pkg-5e0cdeca-dev-49f6fb2b6eef1691264d25b1b9b194ff708144a5-pr-415` image and report back in #415

**Comment by hodindorian** [comment]
Still have the issue with lspipepr/swag:2.7.0-pkg-5e0cdeca-dev-49f6fb2b6eef1691264d25b1b9b194ff708144a5-pr-415 and lspipepr/swag:2.7.0-PR-415 with cloudflare and deploy with Portainer, I test 6 different version and still have the Please set the DNSPLUGIN error

**Comment by cohenchris** [comment]
Please update to a more recent version, this was fixed after 2.7.0.

See [here](https://github.com/linuxserver/docker-swag/issues/414)

**Comment by martinmiglio** [comment]
Still seeing issue this running on these containers: 
```
lscr.io/linuxserver/swag:2.8.0-ls263
lspipepr/swag:2.7.0-pkg-5e0cdeca-dev-49f6fb2b6eef1691264d25b1b9b194ff708144a5-pr-415
```

With these variables set
```.env
VALIDATION=dns
DNSPLUGIN=google-domains
```

**Comment by toddke** [comment]
Switched to latest and appears to be working for me. Thank you!

`
dns validation via google-domains plugin is selected
Certificate exists; parameters unchanged; starting nginx
`

**Comment by cybericius** [comment]
I have 2.8.0 and still have the issue with dynu.

I noticed this in the release note: 
11.12.23: - Deprecate certbot-dns-dynu to resolve dependency conflicts with other plugins.
Can you please explain if it has any connection?

Freezing here:
`Please set the DNSPLUGIN variable to one of the following:`

**Comment by j0nnymoe** [comment]
Dynu has been removed from swag.

**Comment by cybericius** [comment]
Sad to hear that... Not considering adding it back? (2.6.0 works with it perfectly)
If not, do you have any suggested alternative that supports free CNAME and TXT records?
Thank you.

**Comment by thespad** [comment]
The plugin author has abandoned the project and it no longer works with the versions of dependencies that all other plugins need, which is why we removed it.

**Comment by cybericius** [comment]
Where is that plugin? I'd look into it, perhaps can be taken over and updated.
It would be a huge loss, as I cannot find any other DDNS provider that gives for free both CNAME records and TXT record validation through acme...

**Comment by thespad** [comment]
https://github.com/bikram990/certbot-dns-dynu

**Comment by kinslayer1982** [comment]
Too bad, I wanted to switch to using swag from my own setup. But I'm using Dynu and moving to a different DDNS is not an option for me. For now I am using ACME.sh in my setup, they have a working Dynu plugin, maybe this can help somehow?

**Comment by thespad** [comment]
Unfortunately not, certbot and acme.sh using different plugin systems.

**Comment by Roxedus** [comment]
https://github.com/linuxserver/docker-swag#certbot-plugins

**Comment by kinslayer1982** [comment]
I thought I had stumbled over this part but somehow didn't find it again.
But now I'm confused. I thought Dynu plugin is broken. Did I get that wrong?

**Comment by Roxedus** [comment]
Installing it breaks all other up-to-date plugins.

**Comment by DustyRah** [comment]
Dynu has created a ticket to take over the project and update the dependencies but until such time we take it over. We will release updated version of the plugin as soon as project is claimed.

[https://github.com/pypi/support/issues/3520](https://github.com/pypi/support/issues/3520)

**Comment by kinslayer1982** [comment]
> Dynu has created a ticket to take over the project and update the dependencies but until such time we take it over. We will release updated version of the plugin as soon as project is claimed.
> 
> [pypi/support#3520](https://github.com/pypi/support/issues/3520)

Glad to hear that!

**Comment by DustyRah** [comment]
We have been unable to take over the project since no one has been assigned to the ticket. We have created a new project below. Can someone please add support for Dynu in Swag again?

https://pypi.org/project/certbot-dns-dynudns/

**Comment by crltc** [comment]
I am experiencing the same issue using any version including latest.

Container exits with Log File:

`Please set the DNSPLUGIN variable to one of the following:`

Fixes Attempted:
- Confirm my configuration through docker is identical to the one shown on the readme
-  Included the relevant CAP_ADD
- Have tried running as root and giving full permissions on the host volume with no luck. 
- The dns-conf folder used to be populated with .ini file examples of every provider but now when I deploy the image it does not populate any. 
- Recreated the volume entirely

**Comment by gadolf66** [comment]
Hi.
I experience this bug on version 2.10.
Reverting to version 2.9.0 fixed the problem.

**Comment by thespad** [comment]
Your issue is likely unrelated to this one, please open a new issue and provide the necessary information.
